Artist.destroy_all
Album.destroy_all
Question.destroy_all

# ROCK #

# artists #
metallica = Artist.create(name: "Metallica")
iron_maiden = Artist.create(name: "Iron Maiden")
deep_purple = Artist.create(name: "Deep Purple")
dream_theater = Artist.create(name: "Dream Theater")
nirvana = Artist.create(name: "Nirvana")
soundgarden = Artist.create(name: "Soundgarden")
pantera = Artist.create(name: "Pantera")
led_zeppelin = Artist.create(name: "Led Zeppelin")
pink_floyd = Artist.create(name: "Pink Floyd")
korn = Artist.create(name: "Korn")
deftones = Artist.create(name: "Deftones")



# albums #
ride_the_lighting = Album.create(title: "Ride the Lightning", artist: metallica, genre: "Rock")
black_album = Album.create(title: "Black Album", artist: metallica, genre: "Rock")
master_of_puppets = Album.create(title: "Master of Puppets", artist: metallica, genre: "Rock")
kill_em_all = Album.create(title: "Kill 'Em All", artist: metallica, genre: "Rock")
fear_of_the_dark = Album.create(title: "Fear of the Dark", artist: iron_maiden, genre: "Rock")
the_number_of_the_beast = Album.create(title: "The Number of the Beast", artist: iron_maiden, genre: "Rock")
brave_new_world = Album.create(title: "Brave New World", artist: iron_maiden, genre: "Rock")
burn = Album.create(title: "Burn", artist: deep_purple, genre: "Rock")
perfect_stanger = Album.create(title: "Perfect Stanger", artist: deep_purple, genre: "Rock")
made_in_japan = Album.create(title: "Made in Japan", artist: deep_purple, genre: "Rock")
in_Rock = Album.create(title: "In Rock", artist: deep_purple, genre: "Rock")
images_and_words = Album.create(title:"Images and Words", artist: dream_theater, genre: "Rock")
awake = Album.create(title: "Awake", artist: dream_theater, genre: "Rock")
six_degrees = Album.create(title:"Six Degrees of Inner Turbolence", artist: dream_theater, genre: "Rock")
in_utero = Album.create(title: "In Utero", artist: nirvana, genre: "Rock")
bleach = Album.create(title: "Bleach", artist: nirvana, genre: "Rock")
nevermind = Album.create(title: "Nevermind", artist: nirvana, genre: "Rock")
superunknown = Album.create(title: "Superunknown", artist: soundgarden, genre: "Rock")
kind_animal = Album.create(title: "King Animal", artist: soundgarden, genre: "Rock")
down_on_the_upside = Album.create(title: "Down on the Upside", artist: soundgarden, genre: "Rock")
far_beyond_driven = Album.create(title: "Far Beyond the Upside", artist: pantera, genre: "Rock")
power_metal = Album.create(title: "Power Metal", artist: pantera, genre: "Rock")
cowboys_from_hell = Album.create(title: "Cowboys from Hell", artist: pantera, genre: "Rock")
wish_you_were_here = Album.create(title: "Wish You Were Here", artist: pink_floyd, genre: "Rock")
animals = Album.create(title: "Animals", artist: pink_floyd, genre: "Rock")
pulse = Album.create(title: "Pulse", artist: pink_floyd, genre: "Rock")
the_wall = Album.create(title: "The Wall", artist: pink_floyd, genre: "Rock")
follow_the_leader = Album.create(title: "Follow the Leader", artist: korn, genre: "Rock")
issues = Album.create(title: "Issues", artist: korn, genre: "Rock")
untouchables = Album.create(title: "Untouchables", artist: korn, genre: "Rock")
white_pony = Album.create(title: "White Pony", artist: deftones, genre: "Rock")
around_the_fur = Album.create(title: "Around the Fur", artist: deftones, genre: "Rock")
diamond_eyes = Album.create(title: "Diamond Eyes", artist: deftones, genre: "Rock")

# POP #

# artists #
beyonce = Artist.create(name: "Beyonce")
britney = Artist.create(name: "Britney Spears")
christina = Artist.create(name: "Christina Aguilera")
katy = Artist.create(name: "Katy Perry")
kylie = Artist.create(name: "Kylie Minogue")
gaga = Artist.create(name: "Lady Gaga")
madonna = Artist.create(name: "Madonna")
mariah = Artist.create(name: "Mariah Carey")
swift =  Artist.create(name: "Taylor Swift")


# albums #
be1 = Album.create(title: "Dangerously in Love", artist: beyonce, genre: "Pop")
be2 = Album.create(title: "B'Day", artist: beyonce, genre: "Pop")
be3 = Album.create(title: "I Am... Sasha Fierce", artist: beyonce, genre: "Pop")
be4 = Album.create(title: "4", artist: beyonce, genre: "Pop")
#be5 = Album.create(title: "Beyoncé", artist: beyonce, genre: "Pop")
be6 = Album.create(title: "Lemonade", artist: beyonce, genre: "Pop")

br1 = Album.create(title: "...Baby One More Time", artist: britney, genre: "Pop")
br2 = Album.create(title: "Oops!... I Did It Again", artist: britney, genre: "Pop")
#br3 = Album.create(title: "Britney", artist: britney, genre: "Pop")
br4 = Album.create(title: "In the Zone", artist: britney, genre: "Pop")
br5 = Album.create(title: "Blackout", artist: britney, genre: "Pop")
br6 = Album.create(title: "Circus", artist: britney, genre: "Pop")
br7 = Album.create(title: "Femme Fatale", artist: britney, genre: "Pop")
br8 = Album.create(title: "Britney Jean", artist: britney, genre: "Pop")
br9 = Album.create(title: "Glory", artist: britney, genre: "Pop")

#c1 = Album.create(title: "Christina Aguilera", artist: christina, genre: "Pop")
c2 = Album.create(title: "Mi reflejo", artist: christina, genre: "Pop")
c3 = Album.create(title: "My Kind of Christmas", artist: christina, genre: "Pop")
c4 = Album.create(title: "Stripped", artist: christina, genre: "Pop")
c5 = Album.create(title: "Back to Basics", artist: christina, genre: "Pop")
c6 = Album.create(title: "Bionic", artist: christina, genre: "Pop")
c7 = Album.create(title: "Lotus", artist: christina, genre: "Pop")
c8 = Album.create(title: "Liberation", artist: christina, genre: "Pop")

ka1 = Album.create(title: "One of the Boys", artist: katy, genre: "Pop")
ka2 = Album.create(title: "Teenage Dream", artist: katy, genre: "Pop")
ka3 = Album.create(title: "Prism", artist: katy, genre: "Pop")
ka4 = Album.create(title: "Witness", artist: katy, genre: "Pop")

#ky1 = Album.create(title: "Kylie", artist: kylie, genre: "Pop")
ky2 = Album.create(title: "Enjoy Yourself", artist: kylie, genre: "Pop")
ky3 = Album.create(title: "Rhythm Of Love", artist: kylie, genre: "Pop")
ky4 = Album.create(title: "Let's Get to It", artist: kylie, genre: "Pop")
#ky5 = Album.create(title: "Kylie Minogue", artist: kylie, genre: "Pop")
ky6 = Album.create(title: "Impossible Princess", artist: kylie, genre: "Pop")
ky7 = Album.create(title: "Light Years", artist: kylie, genre: "Pop")
ky8 = Album.create(title: "Fever", artist: kylie, genre: "Pop")
ky9 = Album.create(title: "Body Language", artist: kylie, genre: "Pop")
ky10 = Album.create(title: "X", artist: kylie, genre: "Pop")
ky11 = Album.create(title: "Aphrodite", artist: kylie, genre: "Pop")
ky12 = Album.create(title: "Kiss Me Once", artist: kylie, genre: "Pop")
#ky13 = Album.create(title: "Kylie Christmas", artist: kylie, genre: "Pop")

g1 = Album.create(title: "The Fame", artist: gaga, genre: "Pop")
g2 = Album.create(title: "Born This Way", artist: gaga, genre: "Pop")
g3 = Album.create(title: "ArtPop", artist: gaga, genre: "Pop")
g4 = Album.create(title: "Cheek to Cheek ", artist: gaga, genre: "Pop")
g5 = Album.create(title: "Joanne", artist: gaga, genre: "Pop")

#m1 = Album.create(title: "Madonna", artist: madona, genre: "Pop")
m2 = Album.create(title: "Like a Virgin", artist: madonna, genre: "Pop")
m3 = Album.create(title: "True Blue", artist: madonna, genre: "Pop")
m4 = Album.create(title: "Like a Prayer", artist: madonna, genre: "Pop")
m5 = Album.create(title: "Erotica", artist: madonna, genre: "Pop")
m6 = Album.create(title: "Bedtime Stories", artist: madonna, genre: "Pop")
m7 = Album.create(title: "Ray of Light", artist: madonna, genre: "Pop")
m8 = Album.create(title: "Music", artist: madonna, genre: "Pop")
m9 = Album.create(title: "American Life", artist: madonna, genre: "Pop")
m10 = Album.create(title: "Confessions on a Dance Floor", artist: madonna, genre: "Pop")
m11 = Album.create(title: "Hard Candy", artist: madonna, genre: "Pop")
m12 = Album.create(title: "MDNA", artist: madonna, genre: "Pop")
m13 = Album.create(title: "Rebel Heart", artist: madonna, genre: "Pop")

#mc1 = Album.create(title: "Mariah Carey", artist: maria, genre: "Pop")
mc2 = Album.create(title: "Emotions", artist: mariah, genre: "Pop")
mc3 = Album.create(title: "Music Box", artist: mariah, genre: "Pop")
mc4 = Album.create(title: "Merry Christmas", artist: mariah, genre: "Pop")
mc5 = Album.create(title: "Daydream", artist: mariah, genre: "Pop")
mc6 = Album.create(title: "Butterfly", artist: mariah, genre: "Pop")
mc7 = Album.create(title: "Rainbow", artist: mariah, genre: "Pop")
mc8 = Album.create(title: "Charmbracelet", artist: mariah, genre: "Pop")
mc9 = Album.create(title: "The Emancipation of Mimi", artist: mariah, genre: "Pop")
mc10 = Album.create(title: "E=MC2", artist: mariah, genre: "Pop")
mc11 = Album.create(title: "Memoirs of an Imperfect Angel", artist: mariah, genre: "Pop")
mc12 = Album.create(title: "Merry Christmas II You", artist: mariah, genre: "Pop")
#mc13 = Album.create(title: "Me. I Am Mariah… The Elusive Chanteuse", artist: mariah, genre: "Pop")
mc14 = Album.create(title: "Caution", artist: mariah, genre: "Pop")

ts1 = Album.create(title: "Taylor Swift", artist: swift, genre: "Pop")
ts2 = Album.create(title: "Fearless", artist: swift, genre: "Pop")
ts3 = Album.create(title: "Speak Now", artist: swift, genre: "Pop")
ts4 = Album.create(title: "Red", artist: swift, genre: "Pop")
ts5 = Album.create(title: "1989", artist: swift, genre: "Pop")
ts6 = Album.create(title: "Reputation", artist: swift, genre: "Pop")

# ALBUM_ID
album_ids = Album.all.map { |album| album.id }
album_ids.map { |id| Question.create(album_id: id) }
